### ISSUE TITLE
put or get files that more than 65535 blocks failed

### ISSUE THREAD

**Issue by v2abcd** [sirMackk/py3tftp#1]
RRQProtocol.counter or WRQProtocol.counter should be mod 65536 before use.

**Comment by sirMackk** [comment]
Thanks for bringing this up, sorry for the delayed response @v2abcd . Could you share what tftp client you're using that allows for this functionality? This isn't RFC-standard, but I've seen tftp support rollover like this.

**Comment by v2abcd** [comment]
tftpd32
Home Page: http://tftpd32.jounin.net/

curl may be supported, too.

**Comment by sirMackk** [comment]
Hi @v2abcd, apologies for the really delayed response. I found some time over the holidays, updated the code to allow for roll over, and published [an updated package (py3tftp==1.0.0a0)](https://pypi.python.org/pypi?:action=display&name=py3tftp&version=1.0.0a0). Tested both `put` and `get` using a tftp client :+1:
